#!/usr/bin/env python3
"""
============================================================
  aws_setup.py — AWS Lab Infrastructure Setup Script
  Project: The Leaky Bridge – Hybrid Cloud Attack Vector
============================================================

MODES:
  --setup          Real AWS (cần aws configure)
  --setup --local  LocalStack  (cần Docker)
  --setup --sim    Simulation  (không cần gì cả!) ← DÙNG CÁI NÀY

USAGE:
  python aws_setup.py --setup --sim      # Chạy ngay, không cần AWS/Docker
  python aws_setup.py --teardown --sim   # Dọn dẹp
============================================================
"""

import boto3
import json
import argparse
import sys
import os
import shutil
from pathlib import Path
from datetime import datetime

REGION         = "ap-southeast-1"
BUCKET_NAME    = "corp-sensitive-docs-prod-lab"
IAM_USER       = "svc-backup-agent"
IAM_POLICY     = "SvcBackupAgentS3Policy"
LOCALSTACK_URL = "http://localhost:4566"

# Thư mục giả lập "cloud" trên máy local
SIM_ROOT = Path(__file__).parent / "simulated-cloud"


def banner():
    print("""
+----------------------------------------------------------+
|     THE LEAKY BRIDGE -- AWS Lab Setup Script             |
|     [!] EDUCATIONAL USE ONLY -- ISOLATED LAB ONLY        |
+----------------------------------------------------------+
    """)


# ════════════════════════════════════════════════════════════
#  SIMULATION MODE — Không cần AWS hay Docker
# ════════════════════════════════════════════════════════════

def setup_sim():
    """
    Tạo toàn bộ môi trường lab ngay trên máy local.
    Giả lập S3 bucket = thư mục, IAM = JSON file, credentials = text file.
    """
    banner()
    print("[SIM MODE] Chạy hoàn toàn local — không cần AWS hay Docker\n")

    # ── Step 1: Tạo "S3 bucket" (= thư mục local) ─────────────
    print(f"[1/4] Tạo S3 bucket giả lập: s3://{BUCKET_NAME}/")
    bucket_dir = SIM_ROOT / "s3" / BUCKET_NAME
    bucket_dir.mkdir(parents=True, exist_ok=True)

    # Metadata giả lập
    meta = {
        "BucketName": BUCKET_NAME,
        "Region": REGION,
        "CreationDate": datetime.now().isoformat(),
        "AccessControl": "private",
        "PublicAccessBlock": {
            "BlockPublicAcls": True,
            "RestrictPublicBuckets": True
        }
    }
    (bucket_dir / "_bucket_meta.json").write_text(json.dumps(meta, indent=2))
    print(f"    ✓ Bucket '{BUCKET_NAME}' created (private)")

    # ── Step 2: Upload sensitive files ────────────────────────
    print("[2/4] Upload file nhạy cảm lên S3 giả lập...")
    data_dir = Path(__file__).parent / "s3-bucket-contents"
    for src in data_dir.glob("*"):
        if src.is_file():
            shutil.copy(src, bucket_dir / src.name)
            size = src.stat().st_size
            print(f"    ✓ s3://{BUCKET_NAME}/{src.name}  ({size} bytes)")

    # ── Step 3: Tạo IAM User ──────────────────────────────────
    print(f"[3/4] Tạo IAM User: {IAM_USER}")
    iam_dir = SIM_ROOT / "iam" / "users" / IAM_USER
    iam_dir.mkdir(parents=True, exist_ok=True)

    # ❌ Overly-permissive policy (intentional misconfiguration)
    policy = {
        "Version": "2012-10-17",
        "Statement": [{
            "Sid": "AllowS3ReadAll",
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:ListBucket",
                "s3:ListAllMyBuckets",   # ← Too broad!
                "s3:GetBucketLocation"
            ],
            "Resource": "*"              # ← Violates Least Privilege!
        }]
    }
    (iam_dir / f"{IAM_POLICY}.json").write_text(json.dumps(policy, indent=2))
    print(f"    ✓ IAM User '{IAM_USER}' created")
    print(f"    ⚠ Policy: s3:* on Resource:* — intentional misconfiguration!")

    # ── Step 4: Generate Access Keys (giả lập) ───────────────
    print(f"[4/4] Tạo Access Keys cho {IAM_USER}...")

    # Key giả lập — format đúng chuẩn AWS (AKIA + 16 ký tự)
    fake_key    = "AKIASIMULATEDKEY0001"
    fake_secret = "SimulatedSecretKey/ABCDEFGHIJ1234567890+sim"

    # Lưu vào generated_credentials.txt
    creds_path = Path(__file__).parent / "generated_credentials.txt"
    creds_path.write_text(
        f"# Generated by aws_setup.py --sim on {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
        f"# IAM User : {IAM_USER}\n"
        f"# NOTE     : Simulated credentials — for local lab only\n\n"
        f"[{IAM_USER}]\n"
        f"aws_access_key_id     = {fake_key}\n"
        f"aws_secret_access_key = {fake_secret}\n"
        f"region                = {REGION}\n"
    )

    # Cũng đặt vào simulated-fs để giả lập file bị lộ trên web server
    leaked_path = Path(__file__).parent.parent / \
                  "vulnerable-app" / "simulated-fs" / "home" / "ubuntu" / ".aws" / "credentials"
    leaked_path.parent.mkdir(parents=True, exist_ok=True)
    leaked_path.write_text(
        f"[default]\n"
        f"aws_access_key_id     = {fake_key}\n"
        f"aws_secret_access_key = {fake_secret}\n"
        f"region                = {REGION}\n\n"
        f"# NOTE (left by dev): Temporary credentials for svc-backup-agent.\n"
        f"# TODO: Rotate these after the migration sprint — Q3 2024\n"
        f"# DO NOT commit this file. (Oops — already did on 2024-08-15)\n"
    )

    print(f"    ✓ Access Key ID    : {fake_key}")
    print(f"    ✓ Credentials file : {creds_path}")
    print(f"    ✓ Leaked copy      : {leaked_path}")

    # ── Summary ───────────────────────────────────────────────
    print("\n" + "═" * 60)
    print("✅ LAB SETUP COMPLETE (Simulation Mode)")
    print("═" * 60)
    print(f"\n  Simulated S3 Bucket:")
    print(f"    {bucket_dir}")
    for f in bucket_dir.glob("*.csv"):
        print(f"    └─ {f.name}  ({f.stat().st_size} bytes)")

    print(f"\n  Simulated IAM User : {IAM_USER}")
    print(f"  Policy file        : {iam_dir / (IAM_POLICY + '.json')}")
    print(f"  Credentials        : {creds_path}")

    print("\n  ── NEXT STEPS ──────────────────────────────────────")
    print("  1. Chạy attack scripts:")
    print("       python ../attack/02_lfi_exploit.py --sim")
    print("       python ../attack/03_cloud_pivot.py --sim")
    print("  2. Hoặc demo thủ công:")
    print(f"       Mở: {bucket_dir}")
    print(f"       Đọc credentials: {creds_path}")
    print("═" * 60 + "\n")


def teardown_sim():
    """Xóa toàn bộ thư mục simulated-cloud."""
    banner()
    print("⚠  TEARING DOWN Simulation Lab...\n")

    if SIM_ROOT.exists():
        shutil.rmtree(SIM_ROOT)
        print(f"    ✓ Deleted: {SIM_ROOT}")
    else:
        print(f"    ⚠ Không tìm thấy {SIM_ROOT} — đã xóa rồi?")

    creds_path = Path(__file__).parent / "generated_credentials.txt"
    if creds_path.exists():
        creds_path.unlink()
        print(f"    ✓ Deleted: {creds_path}")

    print("\n✅ TEARDOWN COMPLETE\n")


# ════════════════════════════════════════════════════════════
#  LocalStack & Real AWS helpers (giữ nguyên từ trước)
# ════════════════════════════════════════════════════════════

def get_session(region: str, local: bool) -> boto3.Session:
    if local:
        print("    [MODE] LocalStack — http://localhost:4566")
        return boto3.Session(
            aws_access_key_id="test",
            aws_secret_access_key="test",
            region_name=region,
        )
    print("    [MODE] Real AWS — ~/.aws/credentials")
    return boto3.Session(region_name=region)


def get_clients(session: boto3.Session, local: bool):
    kwargs = {"endpoint_url": LOCALSTACK_URL} if local else {}
    return (
        session.client('s3',  **kwargs),
        session.client('iam', **kwargs),
        session.client('sts', **kwargs),
    )


def setup_lab(region=REGION, local=False):
    banner()
    session      = get_session(region, local)
    s3, iam, sts = get_clients(session, local)

    print(f"[1/4] Creating S3 bucket: {BUCKET_NAME}")
    try:
        if region == "us-east-1":
            s3.create_bucket(Bucket=BUCKET_NAME)
        else:
            s3.create_bucket(
                Bucket=BUCKET_NAME,
                CreateBucketConfiguration={'LocationConstraint': region}
            )
        s3.put_public_access_block(
            Bucket=BUCKET_NAME,
            PublicAccessBlockConfiguration={
                'BlockPublicAcls': True, 'IgnorePublicAcls': True,
                'BlockPublicPolicy': True, 'RestrictPublicBuckets': True
            }
        )
        print(f"    ✓ Bucket '{BUCKET_NAME}' created")
    except Exception as e:
        if "BucketAlreadyOwnedByYou" in str(e) or "BucketAlreadyExists" in str(e):
            print(f"    ⚠ Bucket already exists — continuing")
        else:
            print(f"    ✗ Error: {e}")
            sys.exit(1)

    print("[2/4] Uploading files...")
    data_dir = Path(__file__).parent / "s3-bucket-contents"
    for f in data_dir.glob("*"):
        if f.is_file():
            s3.upload_file(str(f), BUCKET_NAME, f.name)
            print(f"    ✓ s3://{BUCKET_NAME}/{f.name}")

    print(f"[3/4] Creating IAM User: {IAM_USER}")
    try:
        iam.create_user(UserName=IAM_USER)
        print(f"    ✓ User '{IAM_USER}' created")
    except Exception as e:
        print(f"    ⚠ {e}")

    policy = {
        "Version": "2012-10-17",
        "Statement": [{
            "Sid": "AllowS3ReadAll", "Effect": "Allow",
            "Action": ["s3:GetObject", "s3:ListBucket",
                       "s3:ListAllMyBuckets", "s3:GetBucketLocation"],
            "Resource": "*"
        }]
    }
    iam.put_user_policy(UserName=IAM_USER, PolicyName=IAM_POLICY,
                        PolicyDocument=json.dumps(policy))
    print(f"    ✓ Overly-permissive policy attached")

    print(f"[4/4] Generating Access Keys...")
    resp = iam.create_access_key(UserName=IAM_USER)
    key  = resp['AccessKey']
    creds_path = Path(__file__).parent / "generated_credentials.txt"
    creds_path.write_text(
        f"[{IAM_USER}]\n"
        f"aws_access_key_id     = {key['AccessKeyId']}\n"
        f"aws_secret_access_key = {key['SecretAccessKey']}\n"
        f"region                = {region}\n"
    )
    print(f"    ✓ Key: {key['AccessKeyId']}")
    print(f"    ✓ Saved: {creds_path}")
    print("\n✅ SETUP COMPLETE\n")


def teardown_lab(region=REGION, local=False):
    banner()
    print("⚠  TEARING DOWN LAB...\n")
    session      = get_session(region, local)
    s3, iam, sts = get_clients(session, local)

    try:
        print(f"[1/3] Deleting bucket: {BUCKET_NAME}")
        paginator = s3.get_paginator('list_objects_v2')
        for page in paginator.paginate(Bucket=BUCKET_NAME):
            objs = [{'Key': o['Key']} for o in page.get('Contents', [])]
            if objs:
                s3.delete_objects(Bucket=BUCKET_NAME, Delete={'Objects': objs})
        s3.delete_bucket(Bucket=BUCKET_NAME)
        print(f"    ✓ Bucket deleted")
    except Exception as e:
        print(f"    ⚠ {e}")

    try:
        print(f"[2/3] Cleaning up IAM: {IAM_USER}")
        for k in iam.list_access_keys(UserName=IAM_USER)['AccessKeyMetadata']:
            iam.delete_access_key(UserName=IAM_USER, AccessKeyId=k['AccessKeyId'])
        iam.delete_user_policy(UserName=IAM_USER, PolicyName=IAM_POLICY)
        iam.delete_user(UserName=IAM_USER)
        print(f"    ✓ User deleted")
    except Exception as e:
        print(f"    ⚠ {e}")

    print("[3/3] Cleaning local files...")
    creds = Path(__file__).parent / "generated_credentials.txt"
    if creds.exists():
        creds.unlink()
        print(f"    ✓ Deleted {creds}")
    print("\n✅ TEARDOWN COMPLETE\n")


# ════════════════════════════════════════════════════════════
#  Entry Point
# ════════════════════════════════════════════════════════════

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="The Leaky Bridge — AWS Lab Setup",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Modes:
  --sim    Pure local simulation — KHÔNG cần AWS hay Docker (khuyên dùng)
  --local  LocalStack mode       — cần Docker đang chạy
  (none)   Real AWS              — cần aws configure

Examples:
  python aws_setup.py --setup --sim       ← Chạy ngay không cần gì
  python aws_setup.py --teardown --sim
  python aws_setup.py --setup --local
  python aws_setup.py --setup
        """
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('--setup',    action='store_true', help='Provision lab')
    group.add_argument('--teardown', action='store_true', help='Destroy lab')
    parser.add_argument('--region',  default=REGION)
    parser.add_argument('--local',   action='store_true', help='Use LocalStack')
    parser.add_argument('--sim',     action='store_true', help='Pure local simulation (recommended)')
    args = parser.parse_args()

    if args.sim:
        if args.setup:
            setup_sim()
        else:
            teardown_sim()
    elif args.setup:
        setup_lab(args.region, args.local)
    else:
        teardown_lab(args.region, args.local)
